/**
 * Imprint design tokens — type-safe references to the CSS custom properties
 * declared in ./tokens.css.
 *
 * This file is hand-maintained to mirror the token NAMES declared in
 * tokens.css. Import "@plimeor/imprint-tokens/tokens.css" for the actual
 * values; use the helpers here to reference tokens from TypeScript/JS.
 */

/** Every CSS custom-property name declared in tokens.css. */
export const tokenNames = [
  '--warm-0',
  '--warm-50',
  '--warm-100',
  '--warm-150',
  '--warm-200',
  '--warm-250',
  '--warm-300',
  '--warm-400',
  '--warm-500',
  '--warm-600',
  '--warm-700',
  '--warm-800',
  '--warm-900',
  '--warm-950',
  '--blue-50',
  '--blue-100',
  '--blue-200',
  '--blue-300',
  '--blue-400',
  '--blue-500',
  '--blue-600',
  '--blue-700',
  '--blue-800',
  '--blue-900',
  '--green-100',
  '--green-300',
  '--green-500',
  '--green-600',
  '--green-700',
  '--amber-100',
  '--amber-300',
  '--amber-500',
  '--amber-600',
  '--red-100',
  '--red-300',
  '--red-500',
  '--red-600',
  '--shadow-rgb',
  '--scrim-rgb',
  '--bg-canvas',
  '--bg-sidebar',
  '--bg-content',
  '--bg-raised',
  '--bg-sunken',
  '--bg-hover',
  '--bg-active',
  '--bg-selection',
  '--fg-primary',
  '--fg-body',
  '--fg-secondary',
  '--fg-tertiary',
  '--fg-disabled',
  '--fg-on-accent',
  '--fg-link',
  '--border-subtle',
  '--border-default',
  '--border-strong',
  '--accent',
  '--accent-hover',
  '--accent-active',
  '--accent-subtle',
  '--accent-fg',
  '--focus-ring',
  '--focus-ring-offset',
  '--success-fg',
  '--success-bg',
  '--success-border',
  '--warning-fg',
  '--warning-bg',
  '--warning-border',
  '--danger-fg',
  '--danger-bg',
  '--danger-border',
  '--danger',
  '--danger-hover',
  '--diff-add-bg',
  '--diff-add-fg',
  '--diff-add-gutter',
  '--diff-del-bg',
  '--diff-del-fg',
  '--diff-del-gutter',
  '--agent-bg',
  '--agent-border',
  '--scrim',
  '--font-ui',
  '--font-read',
  '--font-mono',
  '--text-xs',
  '--text-sm',
  '--text-base',
  '--text-md',
  '--text-lg',
  '--text-xl',
  '--text-2xl',
  '--text-3xl',
  '--text-4xl',
  '--read-body',
  '--read-lh',
  '--lh-tight',
  '--lh-snug',
  '--lh-normal',
  '--lh-relaxed',
  '--w-regular',
  '--w-medium',
  '--w-semibold',
  '--w-bold',
  '--track-tight',
  '--track-normal',
  '--track-wide',
  '--track-caps',
  '--space-0',
  '--space-1',
  '--space-2',
  '--space-3',
  '--space-4',
  '--space-5',
  '--space-6',
  '--space-8',
  '--space-10',
  '--space-12',
  '--space-16',
  '--reading-measure',
  '--sidebar-w',
  '--metadata-w',
  '--topbar-h',
  '--radius-xs',
  '--radius-sm',
  '--radius-md',
  '--radius-lg',
  '--radius-full',
  '--elev-0',
  '--elev-1',
  '--elev-2',
  '--elev-3',
  '--elev-4',
  '--elev-inset',
  '--focus-width',
  '--focus-offset',
  '--ease-standard',
  '--ease-out',
  '--ease-in',
  '--dur-fast',
  '--dur-base',
  '--dur-slow'
] as const

/** A token name known to be declared in tokens.css. */
export type TokenName = (typeof tokenNames)[number]

/**
 * Build a CSS `var()` reference for a known token, e.g.
 * `cssVar("--bg-canvas")` -> `"var(--bg-canvas)"`.
 */
export function cssVar(name: TokenName): string {
  return `var(${name})`
}
