/// anchor-core library — all domain logic, vault I/O, and operation semantics.
///
/// Tauri types do NOT appear in this file or in any pub module below.
/// The Tauri binary (main.rs) is the only consumer of the `tauri` crate.
pub mod agent_fixtures;
pub mod domain;
pub mod operations;
pub mod serve;
pub mod vault;

use serde_json::Value;
use std::path::PathBuf;
use std::sync::Mutex;

// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

#[derive(Default)]
pub struct Model {
    pub agent_tasks: Vec<Value>,
    pub index_status: String,
    pub notes: Vec<Value>,
    pub operations: Vec<Value>,
    pub proposed_changes: Vec<Value>,
    pub vault_path: Option<PathBuf>,
}

// ---------------------------------------------------------------------------
// CoreError — stable error taxonomy used by CLI exit codes + JSON envelope
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub enum CoreError {
    /// Referenced note / resource does not exist.
    NotFound(String),
    /// Optimistic-concurrency revision mismatch (--if-match failed).
    Conflict(String),
    /// Operation is blocked or unsupported in the current mode.
    Blocked(String),
    /// No vault is currently open.
    VaultNotOpen,
    /// Filesystem I/O failure.
    Io(String),
    /// Bad caller input / usage error.
    Usage(String),
}

impl CoreError {
    /// Stable code string used in JSON `{"error":{"code","message"}}` envelopes
    /// and as a basis for CLI exit codes.
    pub fn code(&self) -> &'static str {
        match self {
            CoreError::NotFound(_) => "not_found",
            CoreError::Conflict(_) => "conflict",
            CoreError::Blocked(_) => "blocked",
            CoreError::VaultNotOpen => "vault_not_open",
            CoreError::Io(_) => "io",
            CoreError::Usage(_) => "usage",
        }
    }

    /// CLI exit code mapping (matches the global I/O contract in the plan doc).
    /// 0=ok · 1=usage · 2=not_found · 3=conflict · 4=blocked · 5=vault_not_open · 6=io
    pub fn exit_code(&self) -> i32 {
        match self {
            CoreError::Usage(_) => 1,
            CoreError::NotFound(_) => 2,
            CoreError::Conflict(_) => 3,
            CoreError::Blocked(_) => 4,
            CoreError::VaultNotOpen => 5,
            CoreError::Io(_) => 6,
        }
    }

    pub fn message(&self) -> &str {
        match self {
            CoreError::NotFound(msg)
            | CoreError::Conflict(msg)
            | CoreError::Blocked(msg)
            | CoreError::Io(msg)
            | CoreError::Usage(msg) => msg,
            CoreError::VaultNotOpen => "vault_not_open",
        }
    }
}

impl std::fmt::Display for CoreError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "[{}] {}", self.code(), self.message())
    }
}

impl std::error::Error for CoreError {}

/// Convert a CoreError to the legacy `String` error used by Tauri commands.
/// This preserves the exact string codes the TS frontend already tests for.
impl From<CoreError> for String {
    fn from(err: CoreError) -> String {
        err.message().to_string()
    }
}

// ---------------------------------------------------------------------------
// AnchorState — shared Tauri managed state (declared here so both main.rs and
// agent_fixtures / operations can refer to it without a circular import).
// ---------------------------------------------------------------------------

pub struct AnchorState {
    pub model: Mutex<Model>,
}

impl Default for AnchorState {
    fn default() -> Self {
        Self {
            model: Mutex::new(initial_model()),
        }
    }
}

fn initial_model() -> Model {
    let mut model = Model::default();
    let Ok(workspace_root) = vault::locate_workspace_root() else {
        return model;
    };

    let vault_path = workspace_root.join("desktop/demo/vault");
    // Guard on the committed `notes/` dir, not `.anchor/config` — the .anchor/
    // projection is git-ignored and regenerated by rebuild_vault on load, so the
    // toml is absent on a fresh checkout while the Markdown is always present.
    if vault_path.join("notes").is_dir() {
        if let Err(error) = vault::rebuild_vault(&vault_path, &mut model) {
            eprintln!("failed to restore existing demo vault: {error}");
        }
    }

    model
}

// ---------------------------------------------------------------------------
// Pure core functions — no Tauri types, operate on &mut Model + &Path
// ---------------------------------------------------------------------------
//
// Each function is the pure implementation extracted from the corresponding
// #[tauri::command]. The command wrappers in main.rs lock the mutex and call
// these directly. Parameters mirror the command args exactly.

pub mod core {
    use super::{CoreError, Model};
    use crate::domain::{
        apply_metadata_patch, create_snippet, extract_links, extract_unlinked_mentions,
        graph_impact_summary, kind, next_id, note_id, note_matches_filters, note_to_summary,
        now_iso, operation_value, proposed_change_from_append, revision, revision_object,
        searchable_text, slugify, string_at, title,
    };
    use crate::vault::{
        append_operation, diagnostics_value, ensure_vault_structure, find_note, find_note_index,
        find_proposed_change_index, rebuild_sqlite_projection, rebuild_vault, require_open_model,
        seed_demo_vault, unique_file_path, write_note_file,
    };
    use chrono::Local;
    use serde_json::{json, Value};
    use std::path::Path;

    // -----------------------------------------------------------------------
    // Diagnostics
    // -----------------------------------------------------------------------

    pub fn diagnostics(model: &Model) -> Result<Value, CoreError> {
        Ok(diagnostics_value(model))
    }

    // -----------------------------------------------------------------------
    // Vault management
    // -----------------------------------------------------------------------

    pub fn open_demo_vault(model: &mut Model) -> Result<Value, CoreError> {
        let workspace_root = crate::vault::locate_workspace_root().map_err(|e| CoreError::Io(e))?;
        let vault = workspace_root.join("desktop/demo/vault");
        seed_demo_vault(&vault).map_err(|e| CoreError::Io(e))?;
        rebuild_vault(&vault, model).map_err(|e| CoreError::Io(e))?;
        Ok(diagnostics_value(model))
    }

    pub fn open_vault(path: String, model: &mut Model) -> Result<Value, CoreError> {
        let vault = std::path::PathBuf::from(&path);
        if vault.as_os_str().is_empty() {
            return Err(CoreError::Usage("missing_vault_path".to_string()));
        }
        ensure_vault_structure(&vault).map_err(|e| CoreError::Io(e))?;
        rebuild_vault(&vault, model).map_err(|e| CoreError::Io(e))?;
        Ok(diagnostics_value(model))
    }

    // -----------------------------------------------------------------------
    // Note reads
    // -----------------------------------------------------------------------

    /// List notes with default status filter: excludes archived and trashed notes.
    /// The Tauri command wrapper calls this directly — signature must not change.
    pub fn list_notes(model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(model
            .notes
            .iter()
            .filter(|note| {
                let status =
                    crate::domain::string_at(&note["metadata"], "status").unwrap_or("active");
                status != "archived" && status != "trashed"
            })
            .map(note_to_summary)
            .collect())
    }

    /// List ALL notes including archived and trashed. Used by CLI opt-in flags.
    /// Not exposed as a Tauri command (no signature constraint).
    pub fn list_notes_all(model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(model.notes.iter().map(note_to_summary).collect())
    }

    pub fn read_note(note_id: String, model: &Model) -> Result<Value, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        find_note(model, &note_id)
            .cloned()
            .map_err(|e| CoreError::NotFound(e))
    }

    pub fn open_today_journal(model: &mut Model, vault: &Path) -> Result<Value, CoreError> {
        let today = Local::now().format("%Y-%m-%d").to_string();

        if let Some(note) = model.notes.iter().find(|note| {
            note["metadata"]["kind"] == "journal" && note["metadata"]["journalDate"] == today
        }) {
            return Ok(note.clone());
        }

        let year = &today[0..4];
        let month = &today[5..7];
        let now = now_iso();
        let body = format!(
            "# {today}\n\n- [ ] Capture today's decisions\n- [ ] Link notes with [[Anchor V1]]\n"
        );
        let metadata = json!({
            "aliases": [],
            "created": now,
            "id": format!("journal_{}", today.replace('-', "_")),
            "journalDate": today,
            "kind": "journal",
            "properties": {},
            "tags": ["journal"],
            "title": today,
            "updated": now
        });
        let file_path = format!("journals/{year}/{month}/{today}.md");
        let note =
            write_note_file(vault, &file_path, metadata, &body).map_err(|e| CoreError::Io(e))?;
        model.notes.insert(0, note.clone());

        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "accepted",
            "baseRevisions": {},
            "graphImpactSummary": "Journal created once for local date.",
            "mode": "manual",
            "operationType": "create_journal",
            "provenance": "tauri operation core",
            "resultingRevisions": revision_object(note_id(&note), revision(&note)),
            "targetNoteIds": [note_id(&note)]
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(note)
    }

    // -----------------------------------------------------------------------
    // Note writes
    // -----------------------------------------------------------------------

    pub fn create_note(input: Value, model: &mut Model, vault: &Path) -> Result<Value, CoreError> {
        let title_str = string_at(&input, "title")
            .unwrap_or("Untitled")
            .trim()
            .to_string();
        let body = string_at(&input, "body")
            .map(str::to_string)
            .unwrap_or_else(|| {
                format!(
                    "# {title_str}\n\nWrite from Markdown. Link with [[Anchor V1]] and tag with #idea.\n"
                )
            });
        let now = now_iso();
        let mut metadata = json!({
            "aliases": [],
            "created": now,
            "id": next_id("note"),
            "kind": "note",
            "properties": {},
            "tags": [],
            "title": title_str,
            "updated": now
        });
        if let Some(note_type) = string_at(&input, "type") {
            metadata["type"] = json!(note_type);
        }

        let file_path = format!(
            "notes/{}.md",
            slugify(string_at(&metadata, "title").unwrap_or("untitled"))
        );
        let note = write_note_file(vault, &unique_file_path(vault, &file_path), metadata, &body)
            .map_err(|e| CoreError::Io(e))?;
        model.notes.insert(0, note.clone());

        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "accepted",
            "baseRevisions": {},
            "graphImpactSummary": "New note is available to relation projection after rebuild.",
            "mode": "manual",
            "operationType": "create_note",
            "provenance": "tauri operation core",
            "resultingRevisions": revision_object(note_id(&note), revision(&note)),
            "targetNoteIds": [note_id(&note)]
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(note)
    }

    pub fn update_note(input: Value, model: &mut Model, vault: &Path) -> Result<Value, CoreError> {
        let target_id = string_at(&input, "noteId")
            .ok_or_else(|| CoreError::Usage("missing_note_id".to_string()))?
            .to_string();
        let base_revision = string_at(&input, "baseRevision")
            .ok_or_else(|| CoreError::Usage("missing_base_revision".to_string()))?
            .to_string();
        let index = find_note_index(model, &target_id).map_err(|e| CoreError::NotFound(e))?;
        let before = model.notes[index].clone();

        if revision(&before) != base_revision {
            return Err(CoreError::Conflict("conflict".to_string()));
        }

        let mut metadata = before["metadata"].as_object().cloned().unwrap_or_default();
        if let Some(patch) = input.get("metadataPatch").and_then(Value::as_object) {
            apply_metadata_patch(&mut metadata, patch);
        }
        metadata.insert("updated".to_string(), json!(now_iso()));

        let body = string_at(&input, "body")
            .map(str::to_string)
            .unwrap_or_else(|| before["body"].as_str().unwrap_or_default().to_string());
        let file_path = before["filePath"]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_file_path".to_string()))?
            .to_string();
        let updated = write_note_file(vault, &file_path, Value::Object(metadata), &body)
            .map_err(|e| CoreError::Io(e))?;
        model.notes[index] = updated.clone();

        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "accepted",
            "baseRevisions": revision_object(&target_id, revision(&before)),
            "graphImpactSummary": graph_impact_summary(&before, &updated),
            "mode": "manual",
            "operationType": "update_note",
            "provenance": "local editor save",
            "resultingRevisions": revision_object(&target_id, revision(&updated)),
            "targetNoteIds": [target_id]
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(updated)
    }

    // -----------------------------------------------------------------------
    // Note lifecycle: archive / trash / restore
    // -----------------------------------------------------------------------

    /// Set a note's lifecycle status to "archived" and write atomically.
    /// Archived notes are excluded from list_notes/search_notes by default.
    /// Readable by id via read_note so restore remains possible.
    pub fn archive_note(id: String, model: &mut Model, vault: &Path) -> Result<Value, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let index = find_note_index(model, &id).map_err(|e| CoreError::NotFound(e))?;
        let before = model.notes[index].clone();

        let mut metadata = before["metadata"].as_object().cloned().unwrap_or_default();
        metadata.insert("status".to_string(), json!("archived"));
        metadata.insert("updated".to_string(), json!(now_iso()));

        let body = before["body"].as_str().unwrap_or_default().to_string();
        let file_path = before["filePath"]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_file_path".to_string()))?
            .to_string();
        let updated = write_note_file(vault, &file_path, Value::Object(metadata), &body)
            .map_err(|e| CoreError::Io(e))?;
        model.notes[index] = updated.clone();

        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "accepted",
            "baseRevisions": revision_object(&id, revision(&before)),
            "graphImpactSummary": "Note archived; excluded from default list/search.",
            "mode": "manual",
            "operationType": "archive_note",
            "provenance": "anchor-core cli",
            "resultingRevisions": revision_object(&id, revision(&updated)),
            "targetNoteIds": [id]
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(json!({"id": note_id(&updated), "revision": revision(&updated)}))
    }

    /// Set a note's lifecycle status to "trashed".
    /// Trashed notes are excluded from list_notes/search_notes by default.
    /// Readable by id via read_note so restore remains possible.
    pub fn trash_note(id: String, model: &mut Model, vault: &Path) -> Result<Value, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let index = find_note_index(model, &id).map_err(|e| CoreError::NotFound(e))?;
        let before = model.notes[index].clone();

        let mut metadata = before["metadata"].as_object().cloned().unwrap_or_default();
        metadata.insert("status".to_string(), json!("trashed"));
        metadata.insert("updated".to_string(), json!(now_iso()));

        let body = before["body"].as_str().unwrap_or_default().to_string();
        let file_path = before["filePath"]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_file_path".to_string()))?
            .to_string();
        let updated = write_note_file(vault, &file_path, Value::Object(metadata), &body)
            .map_err(|e| CoreError::Io(e))?;
        model.notes[index] = updated.clone();

        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "accepted",
            "baseRevisions": revision_object(&id, revision(&before)),
            "graphImpactSummary": "Note trashed; excluded from default list/search.",
            "mode": "manual",
            "operationType": "trash_note",
            "provenance": "anchor-core cli",
            "resultingRevisions": revision_object(&id, revision(&updated)),
            "targetNoteIds": [id]
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(json!({"id": note_id(&updated), "revision": revision(&updated)}))
    }

    /// Restore an archived or trashed note to active status by removing the
    /// status key entirely (absent = active, the default).
    /// The note re-appears in list_notes/search_notes after restore.
    pub fn restore_note(id: String, model: &mut Model, vault: &Path) -> Result<Value, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let index = find_note_index(model, &id).map_err(|e| CoreError::NotFound(e))?;
        let before = model.notes[index].clone();

        let mut metadata = before["metadata"].as_object().cloned().unwrap_or_default();
        // Remove the status key entirely — absent means active (the default).
        metadata.remove("status");
        metadata.insert("updated".to_string(), json!(now_iso()));

        let body = before["body"].as_str().unwrap_or_default().to_string();
        let file_path = before["filePath"]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_file_path".to_string()))?
            .to_string();
        let updated = write_note_file(vault, &file_path, Value::Object(metadata), &body)
            .map_err(|e| CoreError::Io(e))?;
        model.notes[index] = updated.clone();

        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "accepted",
            "baseRevisions": revision_object(&id, revision(&before)),
            "graphImpactSummary": "Note restored to active; visible in default list/search.",
            "mode": "manual",
            "operationType": "restore_note",
            "provenance": "anchor-core cli",
            "resultingRevisions": revision_object(&id, revision(&updated)),
            "targetNoteIds": [id]
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(json!({"id": note_id(&updated), "revision": revision(&updated)}))
    }

    // -----------------------------------------------------------------------
    // Search & graph
    // -----------------------------------------------------------------------

    pub fn search_notes(request: Value, model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let query = string_at(&request, "query")
            .unwrap_or("")
            .trim()
            .to_lowercase();
        let limit = request["limit"].as_u64().unwrap_or(30).max(1) as usize;
        let fields = request["fields"]
            .as_array()
            .cloned()
            .unwrap_or_else(|| vec![json!("id"), json!("title"), json!("snippet")]);

        let mut results = Vec::new();
        for note in model
            .notes
            .iter()
            .filter(|note| note_matches_filters(note, &request))
        {
            let searchable = searchable_text(note);
            if !query.is_empty() && !searchable.to_lowercase().contains(&query) {
                continue;
            }

            let mut matched_fields = Vec::new();
            if query.is_empty()
                || string_at(&note["metadata"], "title")
                    .unwrap_or("")
                    .to_lowercase()
                    .contains(&query)
            {
                matched_fields.push(json!("title"));
            }
            if query.is_empty()
                || note["body"]
                    .as_str()
                    .unwrap_or("")
                    .to_lowercase()
                    .contains(&query)
            {
                matched_fields.push(json!("body"));
            }
            if crate::domain::metadata_tags(note)
                .iter()
                .any(|tag| tag.to_lowercase().contains(&query))
            {
                matched_fields.push(json!("tag"));
            }
            if string_at(&note["metadata"], "type")
                .unwrap_or("")
                .to_lowercase()
                .contains(&query)
            {
                matched_fields.push(json!("type"));
            }

            let mut result = json!({
                "id": note_id(note),
                "kind": kind(note),
                "matchedFields": matched_fields,
                "pathHint": note["filePath"],
                "title": title(note),
                "type": note["metadata"].get("type").cloned().unwrap_or(Value::Null)
            });

            if fields.iter().any(|field| field == "snippet") {
                result["snippet"] =
                    json!(create_snippet(note["body"].as_str().unwrap_or(""), &query));
            }
            if fields.iter().any(|field| field == "metadata") {
                result["metadata"] = note["metadata"].clone();
            }
            if fields.iter().any(|field| field == "body") {
                result["body"] = note["body"].clone();
            }
            results.push(result);
        }

        Ok(results.into_iter().take(limit).collect())
    }

    pub fn get_backlinks(note_id: String, model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(extract_links(&model.notes)
            .into_iter()
            .filter(|link| link["resolvedNoteId"] == note_id)
            .collect())
    }

    pub fn get_links(note_id: String, model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(extract_links(&model.notes)
            .into_iter()
            .filter(|link| link["fromNoteId"] == note_id)
            .collect())
    }

    pub fn get_graph_neighborhood(
        target_note_id: String,
        depth: u8,
        model: &Model,
    ) -> Result<Value, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let all_edges: Vec<Value> = extract_links(&model.notes)
            .into_iter()
            .filter(|link| link.get("resolvedNoteId").and_then(Value::as_str).is_some())
            .map(|link| {
                let from = string_at(&link, "fromNoteId").unwrap_or("").to_string();
                let to = string_at(&link, "resolvedNoteId").unwrap_or("").to_string();
                let source = string_at(&link, "source")
                    .unwrap_or("manual_link")
                    .to_string();
                json!({
                    "fromNoteId": from,
                    "graphLayer": if source == "agent_inferred" { "agents" } else { "core" },
                    "id": format!("{}:{}:{}", from, to, source),
                    "source": source,
                    "status": if source == "agent_inferred" { "candidate" } else { "core" },
                    "toNoteId": to,
                    "type": if source == "property_link" { "property" } else { "link" }
                })
            })
            .collect();

        let mut first_hop = std::collections::HashSet::from([target_note_id.clone()]);
        for edge in &all_edges {
            let from = string_at(edge, "fromNoteId").unwrap_or("");
            let to = string_at(edge, "toNoteId").unwrap_or("");
            if from == target_note_id {
                first_hop.insert(to.to_string());
            }
            if to == target_note_id {
                first_hop.insert(from.to_string());
            }
        }

        let mut visible = first_hop.clone();
        if depth == 2 {
            for edge in &all_edges {
                let from = string_at(edge, "fromNoteId").unwrap_or("");
                let to = string_at(edge, "toNoteId").unwrap_or("");
                if first_hop.contains(from) {
                    visible.insert(to.to_string());
                }
                if first_hop.contains(to) {
                    visible.insert(from.to_string());
                }
            }
        }

        let edges: Vec<Value> = all_edges
            .into_iter()
            .filter(|edge| {
                visible.contains(string_at(edge, "fromNoteId").unwrap_or(""))
                    && visible.contains(string_at(edge, "toNoteId").unwrap_or(""))
            })
            .collect();
        let nodes: Vec<Value> = model
            .notes
            .iter()
            .filter(|note| visible.contains(note_id(note)))
            .map(|note| {
                json!({
                    "id": note_id(note),
                    "kind": kind(note),
                    "title": title(note),
                    "type": note["metadata"].get("type").cloned().unwrap_or(Value::Null)
                })
            })
            .collect();

        Ok(json!({ "depth": if depth == 2 { 2 } else { 1 }, "edges": edges, "nodes": nodes }))
    }

    pub fn get_object_types(model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let object_types = [
            ("Project", vec!["status", "repository", "owner"]),
            ("Person", vec!["role", "organization"]),
            ("Book", vec!["author", "status"]),
            ("CodeModule", vec!["repository", "language", "owner"]),
        ];

        Ok(object_types
            .iter()
            .map(|(object_type, properties)| {
                json!({
                    "notes": model.notes.iter()
                        .filter(|note| string_at(&note["metadata"], "type") == Some(*object_type))
                        .map(note_to_summary)
                        .collect::<Vec<_>>(),
                    "recommendedProperties": properties,
                    "type": object_type
                })
            })
            .collect())
    }

    pub fn get_unlinked_mentions(note_id: String, model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(extract_unlinked_mentions(&model.notes, &note_id))
    }

    // -----------------------------------------------------------------------
    // Operation log
    // -----------------------------------------------------------------------

    pub fn list_operation_records(model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(model.operations.clone())
    }

    // -----------------------------------------------------------------------
    // Proposed changes
    // -----------------------------------------------------------------------

    pub fn get_proposed_changes(model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(model.proposed_changes.clone())
    }

    pub fn create_proposed_change(input: Value, model: &mut Model) -> Result<Value, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        let note_id_value = string_at(&input, "noteId")
            .ok_or_else(|| CoreError::Usage("missing_note_id".to_string()))?
            .to_string();
        let note = find_note(model, &note_id_value)
            .cloned()
            .map_err(|e| CoreError::NotFound(e))?;
        let mode = string_at(&input, "mode").unwrap_or("ask");
        let append = string_at(&input, "bodyAppend").unwrap_or("");
        let provenance = string_at(&input, "provenance").unwrap_or("manual proposed change");
        let proposed = proposed_change_from_append(&note, mode, append, provenance);
        model.proposed_changes.insert(0, proposed.clone());
        Ok(proposed)
    }

    pub fn apply_proposed_change(
        id: String,
        model: &mut Model,
        vault: &Path,
    ) -> Result<Value, CoreError> {
        let proposed_index =
            find_proposed_change_index(model, &id).map_err(|e| CoreError::NotFound(e))?;
        let proposed = model.proposed_changes[proposed_index].clone();

        if string_at(&proposed, "approvalState") != Some("pending") {
            return Err(CoreError::Blocked(
                "proposed_change_not_pending".to_string(),
            ));
        }

        let target_id = proposed["targetNoteIds"][0]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_target_note".to_string()))?
            .to_string();
        let note_index = find_note_index(model, &target_id).map_err(|e| CoreError::NotFound(e))?;
        let before = model.notes[note_index].clone();
        let expected_revision = proposed["baseRevisions"][&target_id].as_str().unwrap_or("");
        if revision(&before) != expected_revision {
            return Err(CoreError::Conflict("conflict".to_string()));
        }

        let after = proposed["diff"][0]["after"]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_diff_after".to_string()))?
            .to_string();
        let metadata = before["metadata"].clone();
        let file_path = before["filePath"]
            .as_str()
            .ok_or_else(|| CoreError::Usage("missing_file_path".to_string()))?
            .to_string();
        let updated =
            write_note_file(vault, &file_path, metadata, &after).map_err(|e| CoreError::Io(e))?;
        model.notes[note_index] = updated.clone();
        model.proposed_changes[proposed_index]["approvalState"] = json!("accepted");

        let operation = operation_value(json!({
            "actorId": "internal-dev-agent",
            "actorType": "agent",
            "approvalState": "accepted",
            "baseRevisions": proposed["baseRevisions"].clone(),
            "graphImpactSummary": proposed["graphImpact"].clone(),
            "mode": proposed["mode"].clone(),
            "operationType": "apply_proposed_change",
            "provenance": proposed["provenance"].clone(),
            "resultingRevisions": revision_object(&target_id, revision(&updated)),
            "targetNoteIds": proposed["targetNoteIds"].clone()
        }));
        append_operation(vault, model, operation.clone()).map_err(|e| CoreError::Io(e))?;
        rebuild_sqlite_projection(vault, &model.notes).map_err(|e| CoreError::Io(e))?;
        Ok(json!({ "note": updated, "operation": operation }))
    }

    pub fn reject_proposed_change(
        id: String,
        model: &mut Model,
        vault: &Path,
    ) -> Result<Value, CoreError> {
        let index = find_proposed_change_index(model, &id).map_err(|e| CoreError::NotFound(e))?;
        model.proposed_changes[index]["approvalState"] = json!("rejected");
        let proposed = model.proposed_changes[index].clone();
        let operation = operation_value(json!({
            "actorId": "local-user",
            "actorType": "user",
            "approvalState": "rejected",
            "baseRevisions": proposed["baseRevisions"].clone(),
            "graphImpactSummary": proposed["graphImpact"].clone(),
            "mode": proposed["mode"].clone(),
            "operationType": "reject_proposed_change",
            "provenance": proposed["provenance"].clone(),
            "resultingRevisions": {},
            "targetNoteIds": proposed["targetNoteIds"].clone()
        }));
        append_operation(vault, model, operation).map_err(|e| CoreError::Io(e))?;
        Ok(proposed)
    }

    // -----------------------------------------------------------------------
    // Agent fixtures (pure core wrappers)
    // -----------------------------------------------------------------------

    pub fn list_agent_connections(model: &Model) -> Result<Vec<Value>, CoreError> {
        Ok(vec![
            json!({
                "authState": "not_required",
                "capabilities": ["read_note", "search_notes", "create_reference", "create_proposed_change"],
                "defaultMode": "ask",
                "displayName": "Internal development connection",
                "healthState": if model.vault_path.is_some() { "available" } else { "unavailable" },
                "id": "internal-dev",
                "type": "internal_dev"
            }),
            json!({
                "authState": "unavailable",
                "capabilities": [],
                "defaultMode": "ask",
                "displayName": "ACP adapter checkpoint",
                "healthState": "unavailable",
                "id": "acp-checkpoint",
                "type": "acp_checkpoint"
            }),
            json!({
                "authState": "unavailable",
                "capabilities": [],
                "defaultMode": "ask",
                "displayName": "Built-in provider checkpoint",
                "healthState": "unavailable",
                "id": "provider-checkpoint",
                "type": "built_in_provider_checkpoint"
            }),
        ])
    }

    pub fn list_agent_tasks(model: &Model) -> Result<Vec<Value>, CoreError> {
        require_open_model(model).map_err(|_| CoreError::VaultNotOpen)?;
        Ok(model.agent_tasks.clone())
    }

    pub fn create_agent_task(
        input: Value,
        model: &mut Model,
        vault: &Path,
    ) -> Result<Value, CoreError> {
        // delegate to agent_fixtures module which contains the full implementation
        crate::agent_fixtures::core_create_agent_task(input, model, vault)
    }

    pub fn set_task_permission_mode(
        task_id: String,
        mode: String,
        model: &mut Model,
    ) -> Result<Value, CoreError> {
        crate::agent_fixtures::core_set_task_permission_mode(task_id, mode, model)
    }
}
